// Jenkinsfile — 4-Stage Test Pipeline
// Generated by bestest ci jenkins
//
// 4-stage architecture:
//   1. Fast      — Unit tests (<5min), coverage gate
//   2. Medium    — Integration tests (<20min), retry(3)
//   3. Slow      — E2E / Playwright tests (<60min), retry(3)
//   4. Quality   — Mutation testing / nightly (cron trigger only)
//
// Multi-language monorepo: parallel branches per detected language within each stage.
// Coverage gate reads coverage.target from .bestest/config.yaml (default: 80%).
//
// Prerequisites:
//   - .bestest/config.yaml with ci.enabled=true, ci.provider=jenkins
//   - StackProfile at .bestest/state/stack-profile.json for language detection
//   - Jenkins agents with: Node.js 20+, Python 3.12+, JDK 17+, Go 1.22+
//   - Required plugins: pipeline, workflow-aggregator, credentials-binding

pipeline {
    agent none

    environment {
        COVERAGE_THRESHOLD = '80'
        MUTATION_THRESHOLD = '80'
        NODE_VERSION       = '20'
        PYTHON_VERSION     = '3.12'
        JAVA_VERSION       = '17'
        GO_VERSION         = '1.22'
    }

    options {
        timeout(time: 2, unit: 'HOURS')
        buildDiscarder(logRotator(numToKeepStr: '30'))
        ansiColor('xterm')
    }

    triggers {
        // Nightly build for Stage 4 (Quality)
        cron('0 2 * * *')
    }

    stages {
        // ====================================================================
        // Stage 1: Fast — Unit Tests (parallel per language)
        // ====================================================================
        stage('Fast') {
            parallel {
                stage('Fast – JS/TS') {
                    agent { label 'node' }
                    steps {
                        checkout scm
                        sh 'npm ci'
                        // JUnit XML output path aligns with ci.junit.outputPath from .bestest/config.yaml
                        sh 'mkdir -p .bestest/reports'
                        sh '''
                            npx vitest run --reporter=verbose --reporter=junit --outputFile=.bestest/reports/junit-js.xml src/**/*.test.{ts,tsx} --coverage

                            COVERAGE=$(python3 -c "import json; print(json.load(open('coverage/coverage-summary.json'))['total']['lines']['pct'])")
                            echo "JS/TS Coverage: ${COVERAGE}%"

                            if [ "$(python3 -c "print(1 if float('$COVERAGE') < float('$COVERAGE_THRESHOLD') else 0)")" -eq 1 ]; then
                                echo "ERROR: Coverage ${COVERAGE}% is below threshold ${COVERAGE_THRESHOLD}%"
                                exit 1
                            fi
                        '''
                    }
                    post {
                        always {
                            archiveArtifacts artifacts: 'coverage/**', allowEmptyArchive: true
                            junit '.bestest/reports/junit-js.xml'
                            archiveArtifacts artifacts: '.bestest/reports/**', allowEmptyArchive: true
                        }
                    }
                }

                stage('Fast – Python') {
                    agent { label 'python' }
                    steps {
                        checkout scm
                        sh 'pip install -r requirements.txt pytest pytest-cov 2>/dev/null || pip install pytest pytest-cov'
                        // JUnit XML output path aligns with ci.junit.outputPath from .bestest/config.yaml
                        sh 'mkdir -p .bestest/reports'
                        sh '''
                            pytest tests/unit/ -m unit -v --tb=short --cov --cov-report=json:coverage.json --junitxml=.bestest/reports/junit-python.xml

                            COVERAGE=$(python -c "import json; print(json.load(open('coverage.json'))['totals']['percent_covered'])")
                            echo "Python Coverage: ${COVERAGE}%"

                            if [ "$(python3 -c "print(1 if float('$COVERAGE') < float('$COVERAGE_THRESHOLD') else 0)")" -eq 1 ]; then
                                echo "ERROR: Coverage ${COVERAGE}% is below threshold ${COVERAGE_THRESHOLD}%"
                                exit 1
                            fi
                        '''
                    }
                    post {
                        always {
                            archiveArtifacts artifacts: 'coverage.json', allowEmptyArchive: true
                            junit '.bestest/reports/junit-python.xml'
                            archiveArtifacts artifacts: '.bestest/reports/**', allowEmptyArchive: true
                        }
                    }
                }

                stage('Fast – Java') {
                    agent { label 'java' }
                    steps {
                        checkout scm
                        sh '''
                            if [ -f "gradlew" ]; then
                                ./gradlew test --no-daemon jacocoTestReport
                            elif [ -f "mvnw" ]; then
                                ./mvnw test jacoco:report
                            fi
                        '''
                    }
                    post {
                        always {
                            archiveArtifacts artifacts: 'build/reports/jacoco/**', allowEmptyArchive: true
                            junit 'build/test-results/**/*.xml'
                            archiveArtifacts artifacts: '.bestest/reports/**', allowEmptyArchive: true
                        }
                    }
                }

                stage('Fast – Go') {
                    agent { label 'go' }
                    steps {
                        checkout scm
                        // JUnit XML output path aligns with ci.junit.outputPath from .bestest/config.yaml
                        sh 'mkdir -p .bestest/reports'
                        sh 'go install gotest.tools/gotestsum@latest'
                        sh '''
                            gotestsum --junitfile .bestest/reports/junit-go.xml -- -short -v -coverprofile=coverage.out -covermode=atomic ./...

                            COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
                            echo "Go Coverage: ${COVERAGE}%"

                            if [ "$(python3 -c "print(1 if float('$COVERAGE') < float('$COVERAGE_THRESHOLD') else 0)")" -eq 1 ]; then
                                echo "ERROR: Coverage ${COVERAGE}% is below threshold ${COVERAGE_THRESHOLD}%"
                                exit 1
                            fi
                        '''
                    }
                    post {
                        always {
                            archiveArtifacts artifacts: 'coverage.out', allowEmptyArchive: true
                            junit '.bestest/reports/junit-go.xml'
                            archiveArtifacts artifacts: '.bestest/reports/**', allowEmptyArchive: true
                        }
                    }
                }
            }
        }

        // ====================================================================
        // Stage 2: Medium — Integration Tests (parallel per language, retry)
        // ====================================================================
        stage('Medium') {
            parallel {
                stage('Medium – JS/TS') {
                    agent { label 'node' }
                    steps {
                        checkout scm
                        sh 'npm ci'
                        // JUnit XML output path aligns with ci.junit.outputPath from .bestest/config.yaml
                        sh 'mkdir -p .bestest/reports'
                        retry(3) {
                            sh 'npx vitest run --reporter=verbose --reporter=junit --outputFile=.bestest/reports/junit-js-integration.xml "tests/integration/**"'
                        }
                    }
                    post {
                        always {
                            junit '.bestest/reports/junit-js-integration.xml'
                            archiveArtifacts artifacts: '.bestest/reports/**', allowEmptyArchive: true
                        }
                    }
                }

                stage('Medium – Python') {
                    agent { label 'python' }
                    steps {
                        checkout scm
                        sh 'pip install -r requirements.txt pytest 2>/dev/null || pip install pytest'
                        // JUnit XML output path aligns with ci.junit.outputPath from .bestest/config.yaml
                        sh 'mkdir -p .bestest/reports'
                        retry(3) {
                            sh 'pytest tests/integration/ -m integration -v --tb=short --junitxml=.bestest/reports/junit-python-integration.xml'
                        }
                    }
                    post {
                        always {
                            junit '.bestest/reports/junit-python-integration.xml'
                            archiveArtifacts artifacts: '.bestest/reports/**', allowEmptyArchive: true
                        }
                    }
                }

                stage('Medium – Java') {
                    agent { label 'java' }
                    steps {
                        checkout scm
                        retry(3) {
                            sh '''
                                if [ -f "gradlew" ]; then
                                    ./gradlew integrationTest --no-daemon
                                elif [ -f "mvnw" ]; then
                                    ./mvnw verify -Dgroups="integration"
                                fi
                            '''
                        }
                    }
                }

                stage('Medium – Go') {
                    agent { label 'go' }
                    steps {
                        checkout scm
                        // JUnit XML output path aligns with ci.junit.outputPath from .bestest/config.yaml
                        sh 'mkdir -p .bestest/reports'
                        sh 'go install gotest.tools/gotestsum@latest'
                        retry(3) {
                            sh 'gotestsum --junitfile .bestest/reports/junit-go-integration.xml -- -v -tags=integration ./integration/... ./itest/...'
                        }
                    }
                    post {
                        always {
                            junit '.bestest/reports/junit-go-integration.xml'
                            archiveArtifacts artifacts: '.bestest/reports/**', allowEmptyArchive: true
                        }
                    }
                }
            }
        }

        // ====================================================================
        // Stage 3: Slow — E2E Tests (parallel per language, retry)
        // ====================================================================
        stage('Slow') {
            parallel {
                stage('Slow – JS/TS E2E') {
                    agent { label 'node' }
                    steps {
                        checkout scm
                        sh 'npm ci'
                        sh 'npx playwright install --with-deps'
                        retry(3) {
                            sh 'npx playwright test'
                        }
                    }
                    post {
                        always {
                            archiveArtifacts artifacts: 'playwright-report/**', allowEmptyArchive: true
                        }
                    }
                }

                stage('Slow – Python E2E') {
                    agent { label 'python' }
                    steps {
                        checkout scm
                        sh 'pip install -r requirements.txt pytest playwright 2>/dev/null || pip install pytest playwright'
                        sh 'playwright install --with-deps'
                        retry(3) {
                            sh 'pytest tests/e2e/ -m e2e -v --tb=short'
                        }
                    }
                }

                stage('Slow – Java E2E') {
                    agent { label 'java' }
                    steps {
                        checkout scm
                        retry(3) {
                            sh '''
                                if [ -f "gradlew" ]; then
                                    ./gradlew e2eTest --no-daemon
                                elif [ -f "mvnw" ]; then
                                    ./mvnw verify -Dgroups="e2e"
                                fi
                            '''
                        }
                    }
                }
            }
        }

        // ====================================================================
        // Stage 4: Quality — Mutation Testing (Nightly/Manual only)
        // ====================================================================
        stage('Quality') {
            when {
                anyOf {
                    triggeredBy 'TimerTrigger'
                    triggeredBy cause: "UserIdCause"
                }
            }
            agent { label 'node' }
            steps {
                checkout scm
                sh 'npm ci'
                sh '''
                    npx stryker run

                    SCORE=$(python3 -c "import json; print(json.load(open('reports/mutation/mutation.json')).get('mutationScore', 0))" 2>/dev/null || echo 0)
                    echo "Mutation Score: ${SCORE}%"

                    if [ "$(python3 -c "print(1 if float('$SCORE') < float('$MUTATION_THRESHOLD') else 0)")" -eq 1 ]; then
                        echo "ERROR: Mutation score ${SCORE}% is below threshold 80%"
                        exit 1
                    fi
                '''
            }
        }
    }

    post {
        always {
            echo "Pipeline completed: ${currentBuild.currentResult}"
        }
        failure {
            echo "Pipeline FAILED — check stage logs for details"
        }
        success {
            echo "All stages PASSED — test pipeline green"
        }
    }
}
